# Generated by Django 3.2.8 on 2022-01-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
        ('wishlist', '0001_initial'),
        ('profiles', '0002_postexperienceview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostExperienceView',
        ),
    ]
