# Generated by Django 3.2.8 on 2021-12-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_auto_20211115_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
