# Generated by Django 3.2.8 on 2022-01-09 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_postexperienceview'),
        ('experiences', '0003_alter_experiences_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='profiles.userprofile'),
        ),
    ]
