# Generated by Django 4.0.1 on 2022-01-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_experiences_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
