# Generated by Django 4.0.1 on 2022-01-18 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0008_alter_experiencereview_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencereview',
            options={'ordering': ('created_on',)},
        ),
        migrations.AddField(
            model_name='experiencereview',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencereview',
            name='review_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100),
        ),
    ]
