# Generated by Django 3.2.8 on 2022-01-07 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0003_alter_experiences_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostExperienceView',
            fields=[
                ('experiences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='experiences.experiences')),
            ],
            bases=('experiences.experiences', models.Model),
        ),
        migrations.CreateModel(
            name='ExperienceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.experiences')),
                ('posted_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.experiencelist')),
            ],
        ),
        migrations.AddField(
            model_name='experiencelist',
            name='experiences',
            field=models.ManyToManyField(through='host.ExperienceListItem', to='experiences.Experiences'),
        ),
        migrations.AddField(
            model_name='experiencelist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
